@url = http://localhost:8080/api/albums

### findAll
GET {{url}} HTTP/1.1

### findById (GOOD)
GET {{url}}/album=1&user=1 HTTP/1.1

### findById (BAD)
GET {{url}}/album=999&user=999 HTTP/1.1

### add (GOOD)
POST {{url}} HTTP/1.1
Content-Type: application/json

{
    "artist": "New Art",
    "title": "New Album",
    "firstReleaseDate": "2020-01-01",
    "artUrl": null
}

### add (BAD)
POST {{url}} HTTP/1.1
Content-Type: application/json

{
    "artist": null,
    "title": null,
    "firstReleaseDate": "9999-01-01",
    "artUrl": null
}

### deleteById (GOOD)
DELETE {{url}}/4 HTTP/1.1
